### PR TITLE
Vuepress v1 from etalab/guides

### PR DESCRIPTION
**Pull request by abulte**
This a first try at ejecting the theme from https://github.com/etalab/guides.

Known issue on local env: somehow, `index.md` is not rendered anymore on etalab/guides homepage, instead `README.md` is.

Cf https://github.com/etalab/guides/pull/27 to test the theme on this branch.

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
I tested this with success on https://github.com/etalab/guides/pull/27 🎉Thanks a lot for doing this work!

> Known issue on local env: somehow, index.md is not rendered anymore on etalab/guides homepage, instead README.md is.

I had this issue before (when using etalab/guides with the custom theme within the same repo), only locally, not when deployed using now. No idea why 🤷‍♂ 

Do we drop the online documentation for `v1` or do we change the doc? You only updated the README instructions, removing mentions of an existing documentation website.

**Comment by abulte** [comment]
> I had this issue before (when using etalab/guides with the custom theme within the same repo), only locally, not when deployed using now. No idea why 🤷‍♂

Using both `README.md` and `index.md` is a hack I guess. `vuepress dev` even warns you that it's erasing an existing page. We ought to find a better solution on guides someday, maybe by moving the content to its own folder.

> Do we drop the online documentation for v1 or do we change the doc? You only updated the README instructions, removing mentions of an existing documentation website.

Up to you! I won't do it though ;-)

**Comment by abulte** [comment]
> > Do we drop the online documentation for v1 or do we change the doc? You only updated the README instructions, removing mentions of an existing documentation website.
> 
> Up to you! I won't do it though ;-)

What I _can_ do is extend the README me here to explain the configuration.

**Comment by AntoineAugusti** [comment]
I understand 😉 

Can you add a bit more instructions to the README (likely copy and paste from VuePress) to the README for v1?

I'll see if I can update the demo website to reflect this later on.

**Review by AntoineAugusti — APPROVED** [review]
Ok for me to merge and then tag on npm.

Can you give a quick look at the README file?

**Pull request merged**
